name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build docker image
      run: |
        docker build . --file Dockerfile -t image13

    - name: Show docker images
      run: docker images

    - name: Run Docker container in detached mode
      run: |
        docker run -d --name my-container image13
        docker exec my-container apt-get update && apt-get install -y lynx curl
        docker exec my-container lynx https://www.w3.org
