name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build docker image
      run: |
        IMAGE_TAG="flask-nginx:$(date +%s)"
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Show docker images
      run: docker images

    - name: Run docker container 
      run: echo $IMAGE_TAG
