name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build .. --file Dockerfile --tag flask-nginx:$(date +%s)
    - name: Run Docker container on localhost:80
      run: docker run --name flask-nginx -p 8080:80 flask-nginx
